uploaded_images_path: "data/uploaded_images"
all_images_path: "data/all_photos"
faces_save_path: "data/extracted_faces"
face_embeddings_data_output_folder: "data/face_embeddings"
face_embeddings_data_output_file_path: "face_embeddings_data.pkl"
face_embeddings_data_with_labels_output_file_path: "face_embeddings_data_with_labels.pkl"
vector_store_path: "data/face_embeddings_vector_store"

query_image_folder: "data/query_images/uploaded"
converted_query_image_folder: "data/query_images/jpg_format"
query_image_faces_output_folder: "data/query_faces"
query_in_image_paths_output_folder: "data/query_faces_in_images"
